config/routes.rb
Rails.application.routes.draw do
  root "planes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/block', to: 'application#block'
  get '/unblock', to: 'application#unblock'

  get '/planes', to: 'planes#index'
  get '/plane/:id', to: 'planes#show', as: :plane
  get '/planes/:plane_id/try_to_reserve/:seat_number', to: 'planes#try_to_reserve', as: :try_to_reserve
  post '/planes/reserved', to: 'planes#reserved', as: :reserved

  post 'test_sort_data', to: 'sort#sort_data'
  get '/signup', to: 'users#signup'

  get '/admin', to: 'admin#show'
  post '/admin', to: 'admin#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plane.rb
class Plane
  attr_accessor :id, :name, :seats, :reserved_seats, :from, :to

  MODEL_NAME = 'planes'

  def initialize(id:, name:, seats:, reserved_seats:, from:, to:)
    @id = id
    @name = name
    @seats = seats
    @reserved_seats = reserved_seats
    @from = from
    @to = to
  end

  def self.all
    # @all ||= begin
       response = firebase.get(MODEL_NAME)
       response.body.map do |id, properties|
         data = properties.merge(id: id).symbolize_keys
         Plane.new(data)
       end
     # end
  end

  def self.where(query)
    all.select do |plane|
      query.all? do |property, value|
        plane.send(property) == value
      end
    end
  end

  def self.find(id)
    where(id: id).first
  end

  def self.create(params)
    params[:seats] = params[:seats].to_i.times.map { |i| i }

    plane = new(params)
    plane.send(:save)
  end

  def reserved?(seat)
    reserved_seats.include?(seat.to_s)
  end

  def reserve(seat)
    reserved_seats << seat
    save
  end

  def to_hash
    property_names = self.instance_variables.map do |prop|
      prop.to_s.gsub('@', '')
    end.reject do |prop|
      prop == 'id'
    end

    property_names.inject({}) do |acc, prop|
      acc[prop] = self.send(prop); acc
    end
  end

  private

  def firebase
    Plane.firebase
  end

  def self.firebase
    base_uri = 'https://remotecontrol-35696.firebaseio.com/'

    firebase = Firebase::Client.new(base_uri)
  end

  def save
    if self.id.present?
      firebase.update(MODEL_NAME, "#{self.id}" => self.to_hash)
    else
      firebase.push(MODEL_NAME, self.to_hash)
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def show
  end

  def create
    data = plane_params.merge(
      reserved_seats: [plane_params[:seats].to_i + 1],
      id: nil)

    Plane.create(data.to_h.symbolize_keys)
    redirect_to root_path
  end

  private

  def plane_params
    params.require(:plane).permit([:name, :seats, :from, :to])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from BlockedResource do
    render json: {msg: 'Resource already reserved'}, status: 403, content_type: "application/json"
  end
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  def index
    @planes = Plane.all
  end

  def show
    @plane = Plane.find(params[:id])
  end

  def try_to_reserve
    if plane = Plane.find(params[:plane_id])
      booking = { plane_id: plane.id, plane_name: plane.name, seat_number: params[:seat_number]}
      RemoteControl.reserve_resource(booking)
      session[:booking] = booking

      render json: {}.to_json, status: 200, content_type: "application/json", location: '/testtt'
    else
      render json: {}.to_json, status: 500, content_type: "application/json", location: '/testtt'
    end
  end

  def signup
  end

  def reserved
    booking = session[:booking]
    RemoteControl.free_resource(booking)
    Plane.where(name: booking['plane_name']).first.reserve(booking['seat_number'])

    return redirect_to planes_path
  end

  private
end

app/controllers/sort_controller.rb
class SortController < ApplicationController
  skip_before_action :verify_authenticity_token

  def sort_data
    #curl --data "data=9,8,7,6" -X POST http://localhost:3000/test_sort_data

    data_params = params[:data].split(',').map(&:to_i)
    sorted_data = RemoteControl.spread_calc(data_params)
    render json: sorted_data.to_json, status: 200, content_type: "application/json"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/show.html.erb
<% content_for :page_title do %>
  Cadastrar voo
<% end %>


<%= form_for :plane do |f| %>
  <table class="table table-striped">
    <tbody>
      <tr>
        <th style="text-align: right">Name: </th>
        <td><%= f.text_field :name %></td>
      </tr>

      <tr>
        <th style="text-align: right">Seats: </th>
        <td><%= f.text_field :seats %></td>
      </tr>

      <tr>
        <th style="text-align: right">From: </th>
        <td><%= f.text_field :from %></td>
      </tr>

      <tr>
        <th style="text-align: right">To: </th>
        <td><%= f.text_field :to %></td>
      </tr>

      <tr>
        <th style="text-align: right"><%= f.submit %></th>
        <td></td>
      </tr>
    </tbody>
  </table>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Distributed System</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="nav">
        <%= link_to 'Inicio', root_path, class: 'nav-link active' %>
        <%= link_to 'Cadastrar voo', admin_path, class: 'nav-link active' %>
      </nav>

      <div id="error" class="alert-danger" style="padding: 10px; font-weight: bold; position: fixed; display: none;">errors</div>
      <h2 style="margin: 40px 0"><%= yield :page_title %></h2>
      <%= yield %>
    </div>
  </body>
</html>

app/views/planes/index.html.erb
<% content_for :page_title do %>
  Voos disponíveis
<% end %>

<% if booking = session.delete(:booking) %>
  <div class="card w-75" style="width: 40%; margin-bottom: 40px;">
    <div class="card-body">
      <h4 class="card-title">Booking reserved</h4>
      <p class="card-text">
        Seat <b><%=  booking['seat_number'] %></b> on plane <b><%= booking['plane_name'] %></b> reserved
      </p>

      <%= link_to 'Go to plane page', plane_path(booking['plane_id']), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<div class="row justify-content-md-center">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Seats</th>
        <th scope="col">From</th>
        <th scope="col">To</th>
      </tr>
    </thead>
    <tbody>
      <% @planes.each_with_index do |plane, i|%>
        <tr>
          <th scope="row"><%= i %></th>
          <td>
            <%= link_to plane_path(plane.id) do %>
              <%= plane.name %>
            <% end%>
          </td>
          <td><%= plane.reserved_seats.size - 1 %>/<%= plane.seats.size %></td>
          <td><%= plane.from %></td>
          <td><%= plane.to%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/planes/show.html.erb
<% content_for :page_title do %>
  <%= @plane.name %>
<% end %>

<div class="row justify-content-md-center">
  <% @plane.seats.size.times.each  do |seat| %>
    <div class="col-2 rounded" style="background: #ececec; margin: 5px; padding: 5px">
      <center>
        <div style="width: 110px;">
          <div style="font-size: 12px; margin-bottom: 15px;">
            Banco: <b><%= seat %></b>
          </div>

          <%
            link_options = {
              remote: true,
              role: 'button',
              class: 'btn btn-primary'
            }

            link_options[:class] << ' disabled' if @plane.reserved?(seat)
          %>

          <%= link_to try_to_reserve_path(@plane.id, seat), link_options do %>
            <%= @plane.reserved?(seat) ? 'Reservado' : 'Reservar' %>
          <% end %>
        </div>
      </center>
    </div>
  <% end %>
</div>



<script>
  $('a[data-remote]').on('ajax:success', function(data, as){
    console.log('success');
    console.log(data);
    console.log(as);
    window.location = '<%= signup_path %>';
  }).on('ajax:error', function(data){
    var msg = data['detail'][0]['msg'];
    $('#error').text(msg);
    $('#error').show();
    setTimeout(function(){
      $('#error').text('');
      $('#error').hide();
    }, 5000);
  });
</script>

app/views/users/signup.html.erb
<% content_for :page_title do %>
  Cadastro
<% end %>



<%= form_for :signup, url: reserved_path do |f| %>
  <table class="table table-striped">
    <tbody>
      <tr>
        <th style="text-align: right">Name: </th>
        <td><%= f.text_field :name %></td>
      </tr>

      <tr>
        <th style="text-align: right">Password: </th>
        <td><%= f.text_field :password %></td>
      </tr>

      <tr>
        <th style="text-align: right">Confirm password: </th>
        <td><%= f.text_field :confirm_password %></td>
      </tr>

      <tr>
        <th style="text-align: right">Age: </th>
        <td><%= f.text_field :age %></td>
      </tr>

      <tr>
        <th style="text-align: right"><%= f.submit 'Signup' %></th>
        <td></td>
      </tr>
    </tbody>
  </table>
<% end %>